import Header from "@/components/Header";
import { Lato } from "next/font/google";
import "../globals.css";
import Footer from "./Comp/Footer";
import Review from "./Comp/Review";
import Banner from "./Comp/Banner";
import MoveCard from "./Comp/MoveCard";
import Frequent from "./Comp/Frequent";
import Steps from "./Comp/Steps";
import Final from "./Comp/Final";
import Gallery from "./Comp/Gallery";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main>
          <Header />
          <div className="max-w-4xl mx-auto p-3">{children}</div>

          <Banner />
          <Gallery />
          <MoveCard />

          <Frequent />
          <Final />

          <Footer />
        </main>
      </body>
    </html>
  );
}
